const errorCodes = {
    404: "404",
    IS_REQUIRED: "IS_REQUIRED",
    UNKNOWN_ERROR: "UNKNOWN_ERROR",
    PASSWORD_MISMATCH: "PASSWORD_MISMATCH",
    USER_NOT_FOUND: "USER_NOT_FOUND",
    CODE_IS_NOT_VALID: "CODE_IS_NOT_VALID",
    USER_EMAIL_EXIST: "USER_EMAIL_EXIST",
    PASSWORD_INCORRECT: "PASSWORD_INCORRECT",
    ERR_NETWORK: "ERR_NETWORK",
    REQUEST_NOT_FOUND: "REQUEST_NOT_FOUND",
}
export default errorCodes;